### ISSUE TITLE
Multiple ingredients/recipe views

### ISSUE THREAD

**Issue by LecrisUT** [TandoorRecipes/recipes#1017]
## Background

Depending on where you are viewing a recipe, the available ingredients for a dish varies, not to mention the individual taste and quality of ingredients is different for each region. This becomes crucial for example when pickling food and the available salt (e.g. commercially available pickling salt) acts differently in each country.

Besides the usecase in public servers, it can also be useful in self-hosted environments. E.g. sharing a cookbook with family overseas.

## Proposed solution

Have a selectable view for the ingredients based on the uploader. In cases where the ingredients themselves are changed, or there are fine differences to the recipe itself, a diff of the recipe can be accompanied to generate the other views as well. For public views, it can be useful to track metrics for each view rather than make a separate recipe for each one. It would also be useful to displaced the uploader's region if made public.

**Comment by vabene1111** [comment]
While I see how the proposal could be useful I think it's a little to marginal to justify amount of work that is needed for such a feature. I think the easiest solution for this is to just use the note field for an ingredient and add a "if not available use this" or "careful not to much" or similar. One thing that I would like is alternative ingredients so they integrate better with shopping so that would be similar to what you requested but that is also a lot of work and I don't know when I will be able to make this happen /a priority

**Comment by vabene1111** [comment]
Closing this for now as it is out of scope for the short and mid term future, might revisit this later at a more mature application state

**Comment by smilerz** [comment]
At some point I would like to add a feature that will allow a user to define substitutes which may cover this use case.
