### ISSUE TITLE
"504 Gateway Time-out" - terminated due to signal 9

### ISSUE THREAD

**Issue by BenKan** [TandoorRecipes/recipes#1130]
### Version
Version: 1.0.2

Setup on a Synology NAS 220+

### Bug description
I followed [this setup guide](https://github.com/vabene1111/recipes/files/6901601/Tandoor.on.a.Synology.Disk.Station.pdf) strictly.
Unfortunately, after starting the containers and accessing [my ip].[local port] I get the error "504 Gateway Time-out". 

As mentioned in bug report #1070 I removed all resource limitation, unsuccessfully.

This is the log file from the Tandor_Web container:
[Tandoor_Web.csv](https://github.com/TandoorRecipes/recipes/files/7699073/Tandoor_Web.csv)

**Comment by smilerz** [comment]
did you try setting `DISABLE_TREE_FIX_STARTUP`?

**Comment by BenKan** [comment]
Do I need to set it as a variable in the environment of the Tandoor_Web container?

**Comment by smilerz** [comment]
yes

**Comment by BenKan** [comment]
This gives me the same message "504 Gateway Time-out", again due to signal 9.
[Tandoor_Web.csv](https://github.com/TandoorRecipes/recipes/files/7699113/Tandoor_Web.csv)

**Comment by smilerz** [comment]
Your database isn't accessible.
```
2021-12-12 16:34:00,stdout,	TCP/IP connections on port 5432?
2021-12-12 16:34:00,stdout,	Is the server running on host "Tandoor_DB" (172.18.0.4) and accepting
2021-12-12 16:34:00,stdout,django.db.utils.OperationalError: could not connect to server: Host is unreachable
```

We've seen this on Synology a number of times - I don't know that anyone has determined what the root cause is, or if it is a single root cause.  Double check all of the names and make sure there isn't a typo anywhere.  If that all checks out, various combinations of time, docker restarts and synology reboots typically clear the condition.

**Comment by BenKan** [comment]
Thank you very much for the swift responses. I'll go through it and hope for the best.

**Comment by smilerz** [comment]
Your database isn't accessible.

```
2021-12-12 16:34:00,stdout,	TCP/IP connections on port 5432?
2021-12-12 16:34:00,stdout,	Is the server running on host "Tandoor_DB" (172.18.0.4) and accepting
2021-12-12 16:34:00,stdout,django.db.utils.OperationalError: could not connect to server: Host is unreachable
```

We've seen this on Synology a number of times - I don't know that anyone has determined what the root cause is, or if it is a single root cause. Double check all of the names and make sure there isn't a typo anywhere. If that all checks out, various combinations of time, docker restarts and synology reboots typically clear the condition.

**Comment by smilerz** [comment]
@BenKan are you still experiencing a problem?

**Comment by smilerz** [comment]
closed due to lack of info
