### ISSUE TITLE
Recipe step formatting preview vs viewing the recipe

### ISSUE THREAD

**Issue by Demon-Angelz** [TandoorRecipes/recipes#1152]
Version: 1.0.3

I have added a recipe today, and I am finding the formatting preview very useful but I have come across an issue where the preview in the editor differs in one instance to what can be seen on the recipe page itself.
![image](https://user-images.githubusercontent.com/82278449/146817530-cba8e739-dc3a-4729-a1a8-c06f47acb319.png)

As per above - the preview on the right with my formatting on the left (I was aiming for a nested? bullet point section.
Below you can see that this displays differently.

![image](https://user-images.githubusercontent.com/82278449/146817657-cc967e81-b3eb-4622-b4e6-fc1556c0861e.png)

Another example of this being below.
![image](https://user-images.githubusercontent.com/82278449/146817759-62e88bfc-ef58-4c8e-8ac5-6240dd10fcd3.png)
The preview shows the extra spaces betwen each bullet point (even though not added on the formatting side, but the recipe itself matches the view of the formatting box rather than the preview box.

![image](https://user-images.githubusercontent.com/82278449/146817899-88e6d829-bb91-481d-bf2d-5a78ad361294.png)

**Comment by vabene1111** [comment]
yes this is sadly expected. the preview renders the markdown on the client directly while the recipe view receives pre-rendered markdown from the server which simply uses a different library (since its two different programming languages/systems). I would love to move all rendering to either server or client but i need to weigh some arguments on which option is better and how each of those options would be implemented. 

To be honest that is the reason i left out the preview for so long but i felt like a somewhat accurate preview is still better than none so thats why it is this way right now.
