### ISSUE TITLE
rename Ingredients / food

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1191]
### Version
Version: 1.0.4

### Bug description
In the right top menu the topic is called ingredients
![image](https://user-images.githubusercontent.com/29805669/147828714-25be6322-f937-4b23-a7e3-5c90f56781e9.png)

Inside this topic it is called foods
![image](https://user-images.githubusercontent.com/29805669/147828692-5656baf6-6e02-411f-8e62-b819f5f0941a.png)

The same name would be great.

**Comment by vabene1111** [comment]
thanks for the issue, will fix in the next release

**Comment by shadrqen** [comment]
@vabene1111 This looks like a great first issue for me. Would you mind if I get started with this?

**Comment by vabene1111** [comment]
Sure, take a Crack, shouldn't be too Hard :)

**Comment by shadrqen** [comment]
Great.

**Comment by vabene1111** [comment]
i just fixed this as i had the file open anyway, and i wasn't sure if you would still do it, but thank you for trying. feel free to take a crack at any issue, just let us now below it :)

**Comment by TWART016** [comment]
Inside the recipe there is still Ingredients. Is that wanted?

**Comment by smilerz** [comment]
> Inside the recipe there is still Ingredients. Is that wanted?

Yes. Ingredients are an amount, a unit, a food and a note

**Comment by TWART016** [comment]
> > Inside the recipe there is still Ingredients. Is that wanted?
> 
> Yes. Ingredients are an amount, a unit, a food and a note

I mean in the menu changed the name from ingredients to food. Here is still the old name.

**Comment by smilerz** [comment]
They are ingredients.  Not food.

**Comment by TWART016** [comment]
vabene1111 changed the name in menu from ingredients to food
https://github.com/TandoorRecipes/recipes/issues/1191#issue-1091592620

Inside a recipe the colum named `Food` and the headline is Ingredients
![image](https://user-images.githubusercontent.com/29805669/149109065-a413e1f3-7f65-4cc2-9326-850c8cd7d4f9.png)

What is the difference between these two?

**Comment by smilerz** [comment]
an ingredient is the union of amount/unit/food, the food is just what you put in your mouth.

**Comment by vabene1111** [comment]
its a little confusing but it is right. The table in the recipe is actually the list of ingredients (which are as smilerz said the union of all elements that make up an ingredient). A food is part of the ingredient tuple. Since the menu brings you to the list of foods it is now correctly named foods, the recipe editor allows you to edit actual ingredients thus the header there is right too. 

But thanks for reporting :)

**Comment by shadrqen** [comment]
@vabene1111 I'm sorry for going MIA, couldn't install the app. Had an issue with the database, and later the webpack-stats.json issue described in #1209 However, I've been able to run it successfully by using the vabene111/recipes image instead of building docker locally. I guess I'll be in a position to help now? Thank you.

**Comment by TWART016** [comment]
In Search the name with `Use Tree Selection` enabled is still Ingredients.

And I think the font-size and box size is different.

![image](https://user-images.githubusercontent.com/29805669/151270570-d7d84028-5c6d-411c-a2c5-67c2e4a2584b.png)
![image](https://user-images.githubusercontent.com/29805669/151270585-8842d3db-8c6c-4a03-90e1-6230c83715b7.png)

**Comment by smilerz** [comment]
I don't have an answer for that one - they are using identical placeholder values.  
![Uploading image.png…]()
