### ISSUE TITLE
buttons overlay tabs in shopping list v2

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1243]
### Version
Version: tag develop / shopping list v2

### Bug description
In Safari on iOS the New/Export/Filter buttons overlay the tabs from shopping list v2.
![image](https://user-images.githubusercontent.com/29805669/148314945-cb7ca7d9-5e44-4f72-88b6-b6b3fd932ec0.jpeg)

**Comment by vabene1111** [comment]
thanks for the report, the shopping list is now basically feature complete (or at least everything we target for the first release is in). Since the functional parts are now done we will focus on the UI which simply still needs some polishing. 

closing this as we will definitely pay attention to this.
