### ISSUE TITLE
click on keywords

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1287]
**Is your feature request related to a problem? Please describe.**
Inside a recipe or the search I can see the keywords for recipe. 

**Describe the solution you'd like**
Clicking on the keyword should open the search with this keywords as a filter.

**Comment by vabene1111** [comment]
this is something I wanted to do for a long time but always forgot. Its likely a little tricky on the recipe card as the whole card is clickable but that should be doable by layering the links correctly.

**Comment by vabene1111** [comment]
ok i implemented whats needed for this in the search page and also made the keyword component itself clickable (which already works on the recipe view). Now the recipe card needs to be changed so that everything remains clickable but clicking the keyword pill does not open the recipe but the search for that keyword. 

- [ ] search parameter can be passed and is handled correctly
- [ ] clickable in recipe view
- [ ] clickable in recipe card

**Comment by parkroland** [comment]
Hello I am a current computer science student looking to get into open source development! Is there any chance I can be assigned to finish out this task? Really like the application.

**Comment by smilerz** [comment]
> Hello I am a current computer science student looking to get into open source development! Is there any chance I can be assigned to finish out this task? Really like the application.

feel free to give it a shot
