### ISSUE TITLE
Support for old iPad browsers

### ISSUE THREAD

**Issue by sthuber90** [TandoorRecipes/recipes#1314]
### Is your feature request related to a problem? Please describe.

I have an old iPad with iOS 9.3, which unfortunately doesn't receive any updates anymore. I want to run Tandoor Recipes in Docker on a Raspberry Pi. However, with the current configuration Tandoor Recipes doesn't work within the iPad's browser, i.e. the recipe, recipe search and cookbook pages stay blank, except for the menu, which is always visible.

### Describe the solution you'd like

Tandoor Recipe can be used with old iOS safari browsers (https://browserslist.dev/?q=aW9zX3NhZj49OQ%3D%3D).

### Describe alternatives you've considered

- Let go of the idea of using Tandoor Recipes
- Buying  new tablet (highly unlikely)

### Additional context

I have checked to see if updating the browserslist is enough and update the build script to `vue-cli-service build --modern` as described [here](https://cli.vuejs.org/guide/browser-compatibility.html#browserslist).

```
"browserslist": [
        "> 1%",
        "last 2 versions",
        "not dead",
        "ios_saf>3",
        "safari>2"
],
```

I'm willing to contribute but would need some suggestions on what else needs to be done to get this to work.

### Contribute

- [X] Yes
- [ ] Partly
- [ ] No

**Comment by vabene1111** [comment]
I have no clue on what might be broken on those old browsers. It might even be several things.

There is a project somewhere that enables tandoor to be shown on kindle like devices trough a static render, something like this might one day be introduced into tandoor again but until than I think it is highly unlikely that we will spend the time to support old browsers (I also don't care about old Firefox, Chrome or IE versions because in the current project state it's simply not helping the majority of users)

If it's one special thing that's easy to fix we can certainly change it but I guess it will be quite a few things the old browser does not support. Sorry for your tablet but for now I think the static thing might be best, it was posted in the self-hosted reddit but I am on my phone right now and can't find it, feel free to message me on discord and I will send you a link when I am back home in a few days.

**Comment by smilerz** [comment]
@sthuber90 this is the project @vabene1111 mentioned:
https://github.com/NBPub/RecipeBook-Tandoor
