### ISSUE TITLE
Cannot invite a third user to a paid subscription on https://app.tandoor.dev/

### ISSUE THREAD

**Issue by krafeiner** [TandoorRecipes/recipes#1334]
### Tandoor Version

1.0.4

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

Hosted on https://app.tandoor.dev/ (paid subscription)

### Bug description

I currently have a paid subscription on https://app.tandoor.dev/ that allows three accounts. Two members are already configured (one admin, one user).

After logging into the web UI as the admin user, when clicking on the 'Invite User' button in the 'Space Settings' area, I'm getting an error 'Maximum number of users for this space reached.'. This prevents adding a third user to my paid subscription.

**Comment by vabene1111** [comment]
i am sorry, this is sadly an issue in the current version which has already been fixed but not yet been deployed. If you send me the name of your space, either here or via email to info@tandoor.dev i will increase the limit for your space so you can invite your third user. 

The update should be deployed within the next one or two days otherwise. 

Sorry for the inconvenience, if you have any issues with the paid version you can also always use the support function on tandoor.dev where we are notified directly and might be able to help faster than on github. Also thanks for reporting.

**Comment by krafeiner** [comment]
Hi,

 

The name of the my space is ‘Klaus’, but I’m happy to wait for a few days if this will be updated anyway 😊.

 

Viele Grüße

Klaus Rafeiner

 

Dr. Klaus Rafeiner   -    Kurt-Schumacher-Str. 5   -    D-82110 Germering 

Phone:  +49 89 447 601 78    Mobile: +49 179 13 34 889     Mail:  ***@***.***> ***@***.***

**Comment by vabene1111** [comment]
I have pushed the fixed and started the release workflow, the update will be pushed onto the server in the evening (if i dont forget it 😂 )
