### ISSUE TITLE
export a cook book

### ISSUE THREAD

**Issue by MarcusWolschon** [TandoorRecipes/recipes#1363]
### Describe the solution you'd like

Allow exporting an entire cook book instead of just single receipts or all receipts.
This cook be placed in the context menu of a cook book similat to the "export" entry in the context menu of a single receipt.

### Contribute

- [X] Yes
- [ ] Partly
- [ ] No

**Comment by vabene1111** [comment]
#781

**Comment by MarcusWolschon** [comment]
I don't understand how you work with tickets in this project.
It's certainly handled unlike the backlog of any (Scrum or Kanban) project I've seen.

**Comment by vabene1111** [comment]
Marcus, enough is enough. You have been with this project for a few days at least in an active way. 

In that time you have opened several PRs and not finished them after we added some comments, you have opened countless duplicate issues because you were either unable or unwilling to look trough the existing ones. 
You have asked countless questions that you yourself could have answered by looking a bit trough the code or just testing out things and you have ignored what we together or as maintainers discussed and set out as project goals.

We, who work on this project in our free time, have tried to help, answer your questions, we reviewed and commented your PRs and we even (like in this issue) have pointed you to the appropriate discussions that resolve your issues. We might have a weird way of handling tickets depending on what you are used to but this project has been around for a while and overall our way of working has proven to work (although it always evolves as the project develops)

I do not understand what your problem is but we certainly have the problem that your activity in this project and especially answering to all of the comments (even after we reject certain things) is taking us lots of time that we could otherwise use to improve the project. 

Maybe we just dont understand you /each other, in that case i am very sorry, but given that this is currently causing us a lot of work i would like to ask you to stop contributing to this project (issues, PRs, comments, whatever) unless you can find a way to do it in a constructive way that is in line with our overall project strategy. You are of course welcome do use tandoor and to change it for your personal needs.

**Comment by MarcusWolschon** [comment]
This tone is exactly what I was referring to. As is making accusitions that are obviously wrong as can be seen below with the PRs.

### "overall project strategy"
If there was a way to know what your "overall project strategy" was, I'd be happy to at least read it.
If you differ from the industry standard state flows for tickets (see the default states in Jira, Bitbucket,...) that any random developers learns in university and would expect to find,
it's a good idea to document the states and transitions used in the process as part of the developer documentation.
All I see is undocumented assumptions.

### accusations about tickets
As for the various identified issues and feature requests:
I did not look through the code much as I have no clue about Javascript, I'm only very vaguely familar with Python and the uncommented and undocumented code is hard to read.
I did look through existing ones but things like "allow localized decimals in a serving" and "allow localized decimal separator in a nutritional value" are not the same issue. Same with others.
Standard search only finds issues that are not already closed. Usually meaning either finished or rejected.
It's completely fine to replace 2 or 3 similar issues with a generalized one.
It's completely fine for a ticket to sit in the backlog after getting a priority assigned. Even indefinately.

### accusations about pull requests
The PR that got a request for unit tests did receive unit tests.

The PR for improved develper instructions has no comments and was just waiting for feedback. A simple "thanks, we're a bit busy and will get to it after the next release" would have sufficed. As would be to just update the .md file with your own wording.

The PR about importing nutritional information also has no comments. So there is nothing to do but wait until at some point someone gets around to look at it. Not polite and encouraging donated work but technically fine.

The PR about steps also has no actionable comment but a "i will review this after my vacation and decide how we proceed" wich is completeley fine.
