### ISSUE TITLE
loading in advanced search

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1430]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

In the Advanced Search I see `loading...` if I click on a keywords in recipe and not the keyword.

![image](https://user-images.githubusercontent.com/29805669/151457907-5732dd29-aa04-4ece-8b2f-91d6cd3d4a67.png)

**Comment by vabene1111** [comment]
interesting, for me this is working perfectly fine on the same version. Can you provide the browser logs and maybe take a look at the request panel if any request to /api/keyword fails and what response you get ?

**Comment by smilerz** [comment]
Is the keyword that is still loading a child of another keyword?

**Comment by TWART016** [comment]
In Developer Tools I do not see errors, just warnings
`DevTools failed to load source map: Could not load content for http://192.168.178.15:10005/static/themes/maps/style.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
?keyword=5:359 service worker not in navigator
(anonymous) @ ?keyword=5:359
load (async)
(anonymous) @ ?keyword=5:351`

Where is the request panel?

I uploaded the har file from network tab
[192.168.178.15.har.zip](https://github.com/TandoorRecipes/recipes/files/7961605/192.168.178.15.har.zip)

The keyword is not a child.

**Comment by TWART016** [comment]
It looks like a chrome problem.

Firefox, Edge Chromium and Chrome Incognito is working fine.

**Comment by vabene1111** [comment]
that is interesting because i always use chrome for developing and it works for me in chrome. Whats interesting is that the log you are posting is showing that your service worker is not installed. 

you could reset your site data as shown below and see if it works afterwards (maybe reload 1-2 times without cache afterwards)
![image](https://user-images.githubusercontent.com/6819595/151787375-377adc40-baff-424a-ad72-bcca2a3b1346.png)


this is btw what i meant with request panel but i think you har file came from there (just need to find out how to open it 😂 )
![image](https://user-images.githubusercontent.com/6819595/151787519-c3fce7e2-d959-4d4b-a79a-87a28cea0ea2.png)


usually the request and response tabs are what give me useful information to debug the issues
![image](https://user-images.githubusercontent.com/6819595/151787590-43268032-9716-404e-9991-3bd5822b83de.png)

**Comment by TWART016** [comment]
Has not occurred now. But have also restarted the cache and the browser.

**Comment by vabene1111** [comment]
ok so maybe it was some weird edge case, feel free to re open if anything comes up
