### ISSUE TITLE
Add check all button to shopping list

### ISSUE THREAD

**Issue by 0utl4w** [TandoorRecipes/recipes#1460]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When you add a new meal to the meal plan, there is a check-box at the end of the wizard to add the recipe to the shopping list. Afterwards the meal has a small shopping-basket symbol in the upper left corner of the entry. But the problem is, that the shopping list is empty and you have to add the recipe again.

**Comment by vabene1111** [comment]
have you taken a look at the "new shopping list". Its a button on top of the old one which should have the recipes in it. The old shopping list will be removed with either the next or the update after that

**Comment by 0utl4w** [comment]
No, I used the old shopping list. My problem with the new shopping list is, that it is full with entries from the past (on the tabs "shopping list" and "recipes") I cannot delete... 

And it seems that the new shopping list ist one long list and I cannot create a new empty one anymore. To this moment, I really don't like the new shopping list.

**Comment by 0utl4w** [comment]
Ok, I was able to empty the new shopping list. I had to check all entries under "shopping list" one by one. After 500 clicks... every entry was checked and also the recipes tab was empty. 

Then I retested the points I reported and they worked with the new shopping list. So you can close my two tickets.

**Comment by 0utl4w** [comment]
Nevertheless, I find the chosen solution for the new shopping list unfortunate. 

A button to mark the entire list as done would be extremely practical. Or generally the possibility to create separate lists. Because generally there is the danger that one has old entries on the list, but has forgotten to check them off and has already added new entries via the meal planning. Then you always have to either check off the list entries individually or delete recipes via the recipe list... Multiple shopping lists would also have the advantage that you can access old lists if necessary.

But I understood your new shopping list already better now . Purely from the principle of operation, I found the old one still better, but that is only my personal impression. Maybe I only have to get used to it.

**Comment by vabene1111** [comment]
hmm thats unfortunate, we added a data migration so that the old and new shopping lists are in sync but if the old lists were used but never checked that of course would have filled up the new shopping list dramatically. 

Other than that i see your concern but for us the benefit of not having to worry about the actual list outweight the issues you are describing. If you check of while shopping the new list has the benefit of retaining what you might need to shop next time (for example because you haven't gotten it in the supermarket you went to). But i see one major point which i think we have missed and that is when exporting the list you likely view it as finished and all entries should be checked. I think it would be easy to add an "check all" button either to the top of the list, the context menus or maybe the export dropdown.

what do you think @smilerz

**Comment by smilerz** [comment]
a Check All button should be feasible
