### ISSUE TITLE
openCookLogModal is not defined when trying to open CookLog

### ISSUE THREAD

**Issue by Forceu** [TandoorRecipes/recipes#1541]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Nginx

### Bug description

In the main menu, cooklogs can not be added from the dropdown menu. I am using search style Large

### Relevant logs

```shell
(index):1619 Uncaught ReferenceError: openCookLogModal is not defined
    at HTMLButtonElement.onclick ((index):1619:101)
onclick @ (index):1619
```

**Comment by Forceu** [comment]
Please don't deprecate them! I find it much better than the new one :/

**Comment by Forceu** [comment]
I like the larger overview, the separation of recently viewed recipes and that the remaining recipes are ordered alphabetically. It would be a shame if this view is removed.

**Comment by smilerz** [comment]
> I like the larger overview, the separation of recently viewed recipes and that the remaining recipes are ordered alphabetically. It would be a shame if this view is removed.

recently viewed recipes already exists in the updated search, sorting by name (any many other attributes) will be in the next release.
Adding additional options for recipe cards is possible, if you add a feature request it can be added to the list of future enhancements.  When we upgrade the front-end ( #1511 ) these views will probably be dropped.

**Comment by vabene1111** [comment]
i have not deprecated the old search views because of @Forceu who told me before that he did not like the new one 😂 one main thing i took a way from the last discussion we had was that the sizing/placement of the cards was one of the main concerns and the reason i left the old search views in to this day. 

I tried playing around with the grid because i wanted to make something that allows you to basically define how many cards should in one row and that would change the card automatically to adjust for its size. Sadly i was to much of a front end noob to implement this yet. 

But overall i do not plan to support the old views, i deprecated the old modal recently as it had some flaws and i did not want to spend time fixing them so i guess for now logging when using the old search only works in the recipe view as the new modal cannot be integrated into the old search (its not a vue view). 

I think the only thing, after merging the custom filters update which allow for sorting left is the sizing and styling of recipe cards, then the old search can be removed.
