### ISSUE TITLE
external recipes are no longer visible in the search for version 1.0.5 to 1.08

### ISSUE THREAD

**Issue by favoritefood** [TandoorRecipes/recipes#1565]
### Tandoor Version

1.0.5 and 1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I setup Tandoor Recipes with Docker-Compose. The first installation was made with Tandoor Version 1.0.4. 
I synced some PDF files and they all showed up in the search. Then I updated to Version 1.0.5 and 1.0.8 and in both versions the external recipes are no longer visible in the search. You can still see them in the database but they are not accessible. Even new imported external recipes are not visible. 

With a trick you can see them: 
- Open the admin database view in a new tab and change the flag for an external recipe to internal
- Switch back to the recipe search. Now the recipes shows up. 
- Open the recipe. The pdf file is not visible, because the flag still is internal
- Change back to the admin database view and change the flag pack to external
- Reload the open recipe page. Now the pdf files gets visible.

**Comment by vabene1111** [comment]
thats very interesting, i cant really test that right now since develop is ahead and i cant back migrate my test instance right now but i now its working there so the next release (which will be out in the next couple of days hopefully) should fix this issue.

If not please re open this issue or post a new one so i can investiagte further 

thanks for the detailed report

**Comment by favoritefood** [comment]
Hi vabene1111,

thanks for the quick response and the greate application. Looking forward to the next version.
