### ISSUE TITLE
Aliasing for units to assist with import

### ISSUE THREAD

**Issue by stewartadam** [TandoorRecipes/recipes#167]
**Is your feature request related to a problem? Please describe.**
Importing recipes can be tedious because different websites use slightly different terminology for units (e.g. `tbsp` vs `tablespoon`). It would be great to have aliases for ingredients to auto-import the correct (existing) ingredient if the string matches an alias for an existing recipe.

**Describe the solution you'd like**
1. Editing an existing ingredient exposes a tag-like field (like Keywords on recipes) that permits entering unique strings
2. When importing a recipe, if an ingredient matches an existing alias, import using the existing ingredient instead.

**Describe alternatives you've considered**
Renaming the imported units manually

**Comment by vabene1111** [comment]
hmm this is a very interesting (and nice) idea. Should also be quite easy to do as all the pre-parsing and matching is done on the server anyway.

**Comment by phillipthelen** [comment]
I'd like to work on implementing this. The way I would implement it would be to have a list of aliases on the unit and food edit pages where the user can add them. For example the unit would be "Tbsp" and the aliases would be things like "Tablespoon", "Esslöffel" and so on. And then use that list when parsing the recipes to match the units and foods correctly. When a user adds an ingredient manually and types the unit/food into the selector, it could also use that list of aliases. I think especially for foods this could be useful. Like if you want to add "spring onions" as an ingredient, but forgot that you have them as "Scallions" in the database. Or if multiple people add recipes it would help with that being consistent.

**Comment by vabene1111** [comment]
yes i really like the feature idea. I think the solultion you propose is the easiest one, i am just trying to think if there are any better solutions possible. The only thing i could think of is some kind of generic "rule" system but in the end it would probably either be implemented very similarly to what you propose or be bad from a performance standpoint so yes, i think this is the way to go.

1. add alias models for Food, Unit and probably since those three always come together keywords as well. Since @smilerz is working on making those three pages similar this could even be implemented with the merge feature wer merging say TL and tablespoons would add tablespoons to TL's aliases
2. implement a check in the ingredient parser unit, keyword and food functions that checks if an alias exists
3. modify the Food, Unit, Keywords API Endpoint behavior so that searching for something returns its "parent" object first but also the child in case a user really wants to use the alias

now that i am writing this, another way of implementing this could be to use @smilerz's latest tree system, this would probably be really efficient as the whole tree structure is optimized, but i am not sure if this has any other drawbacks (maybe we are mixing two features which will diminish returns on the other and also this would mean that aliases only work on postgres).

let me know what you think

**Comment by smilerz** [comment]
I would suggest extending the parse_ingredient method to do this instead of modifying units and/or foods.  There are some common use cases where importing mixes unit and food (garlic:clove instead of clove:garlic) or puts word breaks in bad locations.

From a UI perspective, I think that merging two units (oz to ounce for example) should prompt the user to request if they would always like to convert oz to ounce and save the result into the model that storing these settings.  

I had an ImportFactory on my list of enhancements some day that could be configured via the import page, but utilizing merge is a great idea.  some other use cases I considered wanting to handle:
- always putting whatever is in parenthesis into the notes
- divide/multiple servings by X from site Y (I've seen sites make weird choices on serving sizes)
- detect units given in metric and imperial and choose one or the other (probably site specific)
- detect unit and/or food choices (chicken legs or thighs) and prompt for creation of import factory [always first/last choice, always legs, never legs]

I'm sure I had more use cases, but thinking through each of them will help assist creating a model that can be extended over time.

**Comment by vabene1111** [comment]
very interesting, the amount of ideas you present (which are very interesting and likely relevant for others as well) kinda makes the idea of some kind of rule based system seem better. 

i think we should create a concrete technical roadmap before starting to implement these features or start with a very rough implementation to then validate if its properly expandable in the future. I feel like starting with the simple food/unit aliases yields the highest return for the smallest amount of effort but such a system should be build in a way that it support future expansion.

**Comment by smilerz** [comment]
agree with start small, but thinking with future in mind

**Comment by vabene1111** [comment]
ok so i had so many ideas that i need to write them down, feedback very much welcome. Also yes we said easy might be better but creating an alias method for keyword/unit/food is likely as much work as creating a rule system that can be expanded later.

Create new Model `Rules` or `Automations` or something like that.

ChoiceField with Rule Types, those could be the following (with the alias feature being the top priority) 

- Alias for keywords/units/foods, triggered in food model create function or maybe even in the multiselect on the frontend or during import
- clean description on import, filter by import source
- add tags to recipes based on name/source of import/ingredients/...
- add recipes to books based on import source/name/ingredients/...

Once some background handling is implemented #103 one could also add rules based on times, webhooks, intervals, etc.

Rules can also be executed without their normal trigger

What i am not sure about: How to handle rules for normal recipe editing? loading them into the frontend might be a little heavy but processing them on save and simply changing the recipe without the users input seems wrong as well

additional the model would have several generic varchar/text attributes for generic parameters, how those are processed and a short description of each type could be combined into a class that could also display the user some basic information on how to use said rule.

Additionally rules could be automatically created for example when merging ingredients.

**Comment by vabene1111** [comment]
ok so a basic rule system has been implemented that currently processes unit and food aliases when importing (both url and app).
I would still classify it very much in a beta stage but it works from my limited testing. 

TODO
- [ ] proper documentation (best trough a processable class)
- [ ] descide how to handle renaming of food/units/keywords (should aliases change as well, stay the same or be deleted), maybe user choice but then an interfacce needs to be build
- [ ] process keywords
- [ ] decide how to handle rules with normal multiselect inputs (maybe present alias as first result but allow non alias) or maybe add 'strict' parameter to rule which does not allow creation of aliased variant
- [ ] add manual run capability

**Comment by smilerz** [comment]
@vabene1111 not sure if you want this here or create an enhancement.

- [ ] rule to do something with a pattern (regex?  but I hate how complicated regex rules get) this example is stuff in parens gets moved to notes

![image](https://user-images.githubusercontent.com/1808639/134248696-830398ed-c9e9-4a23-a129-9ce58f7c5dc3.png)

this would be  ", shredded" gets appended to notes
![image](https://user-images.githubusercontent.com/1808639/134248817-81aea428-403c-49b3-9efe-b7f1b72e497c.png)

**Comment by smilerz** [comment]
another would be when garlic is unit and clove is food switch them
![image](https://user-images.githubusercontent.com/1808639/134249074-eaf7594d-fd25-4242-82e6-7f8aa98106fc.png)

**Comment by smilerz** [comment]
and another - force some words to stick together, here jalepeno chile is always an ingredient
![image](https://user-images.githubusercontent.com/1808639/134250835-2cc7e25f-67c5-4fa2-901f-b3dcc3ff7806.png)
