### ISSUE TITLE
Too small fractions fail to display entirely

### ISSUE THREAD

**Issue by HarHarLinks** [TandoorRecipes/recipes#1702]
### Tandoor Version

Current Version: 1.1.4 Ref: 0c841ec6862763c82961c3f8bf9ecfdac28e6604

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx

### Bug description

I have a recipe that uses 1/4 cup of an ingredient at 12 portions.
If I scale down to 6 portions, it shows "1/8 cup".
If I scale down to 3 potions, it shows " cup"

**Comment by vabene1111** [comment]
ok so this happens because i have set the highes denominator of the fractions to `10`. I am not that familiar with the "american" cooking units but all recipes i remmeber have not used fractions with higher denominators than 10 because its probably impractical to weight 1/48 of flour or whatever. 

the question is what would be the best way forward. I would probably say its showing decimals once the fractions become to small or do you think that fractions should simply show whatever they are ?

For now I added that the decimal version is returned if the fraction becomes to small, maybe we will add a setting to choose the highest shown denominator (basically the corresponding setting to the number of decimal places for fractions).

**Comment by HarHarLinks** [comment]
> showing decimals once the fractions become to small

that is exactly what I would have proposed.

in reality a more complex system might make sense, e.g. for a unit like Litre, go down to 1/4 but instead of 1/5 Litres just say "200 ml". Maybe for such units with a common smaller unit it always makes sense to switch to the smaller unit. On the other hand a unit like tablespoons TBS it's nicer to have 1/8 of it than 0.125.

Anyway I think your solution is appropriate in my opinion, at least until the whole units system is revised to include conversions (imperial/metric/...) etc.

**Comment by vabene1111** [comment]
perfect, as you said, once conversion and more in depts options for units are added things like "largest denominator" for a unit or "amount of decimals" as a per unit setting will likely be implemented.
