### ISSUE TITLE
Importfilter für Rezepte aus "Einfach Hausgemacht"?

### ISSUE THREAD

**Issue by gitpower2017** [TandoorRecipes/recipes#1742]
### Is your feature request related to a problem? Please describe.

Es können keine Rezepte aus "einfach Hausgemacht" importiert werden

### Describe the solution you'd like

Wer kann einen Importfilter für die Rezepte aus "Einfach Hausgemacht" erstellen?

[(https://www.einfachhausgemacht.de/Backen-1589912.html)]

**Comment by vabene1111** [comment]
the page does not contain any structured data so we cannot import it with the normal parser. You can open an issue on the https://github.com/hhursev/recipe-scrapers repository and kindly ask if someone is willing to implement a parser for that site. Since tandoor uses recipe scrapers it will then become available in tandoor as well.
