### ISSUE TITLE
Merge import and edit 

### ISSUE THREAD

**Issue by RichardHum** [TandoorRecipes/recipes#177]
It would be great if we could have a unified interface for both import and edit. I like some features of the import interface, but I also like the versatility of the edit interface. I would like the ability to edit steps and add notes in the import field, and merging the two interfaces could achieve this.

**Comment by vabene1111** [comment]
yes, this is definitly something that would be nice but also is quite a lot of work/technical difficulties. Could you describe which features of the import interface are lacking in the edit interface that you miss there ?

The biggest problem here honestly is that i am simply not that good at that whole javascript vue.js stuff (yet) to merge these two interfaces completly without creating very messy code.

**Comment by RichardHum** [comment]
I don't like how you can't edit an ingredient in the edit interface. When you start typing, you have to re-type the entire thing. 

The auto-complete is finicky on both interfaces, but that's another issue. If you give me a few pointers on where to start looking, I can definitely try to help modify things. I've got a little bit of Javascript experience.

**Comment by vabene1111** [comment]
if you look at the code you will find that many functions in the various interfaces are similar or straight up duplicates. i first need to find out how to properly move them into components that can be integrated into a view (for example the makeToast()) function. 

After that another big problem is what to do with newly generated entries on the client as thats something i haven't done before. The Problem here is when i add an ingredient in the interface it does not yet have an id in the database. I could generate an entry and delete it if the UI deletes it again but that feels a little stupid. The way i am doing it currently is by generating random IDs and changing them on first DB save to the real ones. This approach has its own problems.

Regarding the multi selects there are several issues. When using only plain django and some js here and there i used (or still use) select2.js. For the vue stuff i moved to `vue-multiselect` which is nice but has some other problems (e.g. no case sensitivity support #170). Maybe there is something better i could use or maybe i am just to stupid to configure it correctly. Also the function for looking up ingredients/units/keywords are similar but not the same on each page which is very annoying and unclean.

If you want to help clean up the JS mess feel free to create a PR, we can also have a quick chat on discord or some other voice service of your liking (discord would be `vabene1111#5492`)
