### ISSUE TITLE
shopping list icon in top navigation bar

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1778]
### Is your feature request related to a problem? Please describe.

I use Tandoor as PWA on iPhone. Currently the home page is hardcoded because of ios restrictions

### Describe the solution you'd like

It would be easier to access shopping list with an icon in the top navigation bar.

![image](https://user-images.githubusercontent.com/29805669/167164135-5e51d562-ab53-42c6-bea7-0f653f7b7aa2.png)

**Comment by TWART016** [comment]
Absolutely correct. 
I never need the `Quick Actions` for example

**Comment by vabene1111** [comment]
yes i had the same problem .. since i am on android i can just add the direct link to my homescreen but sadly iOS does not allow for this. Making the nav configurable would be interesting i guess but also a rather large thing we need to properly think trough/design to allow future modification and expansion (maybe a table in the settings where you can, for each important view, define where its shown)
