### ISSUE TITLE
zoom optimizations

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1779]
### Is your feature request related to a problem? Please describe.

I use Tandoor as PWA on iPhone.

### Describe the solution you'd like

1) In shopping list / New Entry: Clicking in the text field the view zoom in a little inside
![image](https://user-images.githubusercontent.com/29805669/167165624-0fc42a60-c952-4c52-b107-9aff7d16c886.png)

2) zoom out is difficult in shopping list. Accidental deletion or ticking off is very probable
![image](https://user-images.githubusercontent.com/29805669/167165976-4922b642-ec78-468a-9476-37f3b6183818.png)

**Comment by vabene1111** [comment]
the zoom on the input box must be some IOS specific nonesense i think because i dont notice this on android :thinking: But yes the swipe zones need to be overhauled a bit to prevent accidentally swiping, i think @Kaibu is already working on this.

Or are you talking about manually zooming in/out with two fingers ? I think the layout should be in such a way that this is not required.

**Comment by Kaibu** [comment]
I've not set the text-size of those inputs to 16px, there not far off anyway.
Since I dont have any IOS devices, feedback on this fix would be much appreciated!

**Comment by TWART016** [comment]
With 1.2.5 there is no zoom in with clicking in the text field. Thanks.
