### ISSUE TITLE
Meal Plan week view doesn't take up the full page height

### ISSUE THREAD

**Issue by bhdouglass** [TandoorRecipes/recipes#1782]
### Tandoor Version

1.2.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

The meal plan week view does not take up the full height like it did before the v1.2.x release (see attached screenshot). This also happens when on a phone. 

![Screenshot_20220506_161205](https://user-images.githubusercontent.com/935035/167210709-7cb42e55-5fee-4611-b3bc-050e32aba860.png)

I don't have a screenshot from before, but previously it would take up the whole space, down to the buttons.

Side note, Tandoor has been super awesome, thanks!

**Comment by vabene1111** [comment]
hmm @Kaibu is it possible that this is related to an attribute you set for the tandoor theme but not the others ?

@bhdouglass can you test the view with the tandoor theme and tell me if its broken there as well ?

**Comment by bhdouglass** [comment]
Looks like the Tandoor theme also has this problem:

![Screenshot_20220508_081314](https://user-images.githubusercontent.com/935035/167295618-e4e25f3c-e0f2-4449-b544-92caf4272e06.png)

**Comment by sutherlandm** [comment]
I noticed the same problem when on Firefox, tried Chrome and it loads as expected. The issue is still there even in a Firefox private window without any plugins loaded. All themes on Chrome work as expected.

Firefox:
![firefox](https://user-images.githubusercontent.com/8054027/167475864-531258c2-d622-4bd2-85aa-b40ddb14be55.PNG)
 
Chrome:
![chrome](https://user-images.githubusercontent.com/8054027/167475923-c16e084d-3365-4e63-a1cc-9c18cda7f681.PNG)

**Comment by bhdouglass** [comment]
Oh yeah, should have mentioned I'm using Firefox.I just tried Chromium and it works as expected.

**Comment by bhdouglass** [comment]
Works great in v1.2.5, thanks!
