### ISSUE TITLE
 Missing Total_Time when importing Paprika Recipe Manager 3 

### ISSUE THREAD

**Issue by Hausmeister486** [TandoorRecipes/recipes#1799]
### Tandoor Version

1.2.5

### Setup

Unraid

### Reverse Proxy

No reverse proxy

### Bug description

After the import, all recipes are missing the times information

![image](https://user-images.githubusercontent.com/76865047/168166264-42540d8c-8f43-4699-9216-f707c70380ce.png)
#1485 

Number of servings are now corect

**Comment by Hausmeister486** [comment]
Why is this being fixed so late? The times have already worked, if details are missing the imports are as good as useless? I have 230 recipes here that I can use only limited.
It would be nice if this could be fixed faster.

Best regards

**Comment by smilerz** [comment]
If it’s that important make an attempt to fix it yourself.  We are doing this in our free time and for free, this type of attitude is not appreciated, and certainly isn’t going to entice anyone to do it faster.

**Comment by Hausmeister486** [comment]
Yes, I understand that, do not want to annoy anyone here, am also always ready to help support. As I have already done.

**Comment by Hausmeister486** [comment]
Well, it takes as long as it takes, it will probably still take a few months until the next milestone.
Thank you for your work
Best regards

**Comment by vabene1111** [comment]
i really dont understand you attitude here ? I and all other main contributers work full time jobs, have families and sometimes the need to do something else than work all the time. Even given that we improved several importers (including paprika) with the last release and will do so again in the future. 

We have been increadibly lucky to have received very little of what you just did here over the past, which is good because i am certain if it would happen more regularly i would have stopped working on this a long time ago. In the end you waste everyones time with comments like this, time that could be used by us to actually work on things that bring the project forward. 

This will be fixed when we have the time to fix it, if that is not fast enough for you feel free to use any other recipe manager or fix the issue yourself, its likely very easy to fix (could probably be done in the time it took to read and answer to your comments).

**Comment by vabene1111** [comment]
i have just reviewed this and both prep and cook time are imported correctly, total time is not imported as tandoor has no support for total time at the moment. 

Once this is implemented in tandoor (which it will likely in the future) it needs to be added to all importers. #1882
