### ISSUE TITLE
Recipe Import: Adjust the default serving size

### ISSUE THREAD

**Issue by nagua** [TandoorRecipes/recipes#1807]
### Is your feature request related to a problem? Please describe.

When importing a recipe from an app I always get a default serving size of 1. That is rather inconvenient to use. So I have to manually scale all ingredient amounts.

### Describe the solution you'd like

It would be nice to have an option to set the preferred serving size when importing. At least let me set a multiplier for the serving size from the imported recipe and all ingredient amounts.

### Describe alternatives you've considered

Doing it manually. But that is rather inconvenient and time consuming.

**Comment by MeneDev** [comment]
For `recipe-scrapers` the information about the serving size can be obtained with `yields()`.

example:

```python
scraper = scrape_me('https://www.hellofresh.de/recipes/kokos-curry-pfannkuchen-mit-bohnenfullung-646c931607ff0f985705066e')
print('yields', scraper.yields())
```

will print

```
yields 2 servings
```

**Comment by vabene1111** [comment]
this has been implemented since this issue was raised so closing this as done.

**Comment by MeneDev** [comment]
Maybe I misunderstood the problem. When I import e.g. `https://mobile.kptncook.com/recipe/pinterest/Pasta-mit-veganem-Erbsen-Frischk%C3%A4se-Pesto-&-Zitronen-Crunch/5d861832?lang=en`, `recipe-scrapers` will return e.g. `'2.0 tbsp panko breadcrumbs'` and `yields` returns `1`. Yet after the import I get `'2.0 tbsp panko breadcrumbs'` but the Servings are set to 2. So it's only half as much as I would expect. Is this a different bug? If so I can create an issue.

**Comment by vabene1111** [comment]
i am pretty sure this issue is related to the kptcook scraper and also its website as there are conflicting infos given in the page source and on the markup for the user (the UI shows 4 tbsp while the source has 20g for example). 

https://github.com/hhursev/recipe-scrapers/blob/main/recipe_scrapers/kptncook.py 

I think one would need to properly look at the scraper and some examples from the kptncook website and see if all of them return the correct results.
