### ISSUE TITLE
Keep the units and food items in temporary tables when first importing a recipe

### ISSUE THREAD

**Issue by SvenErik1968** [TandoorRecipes/recipes#1855]
### Describe the solution you'd like

When I import a recipe, I often experience that it don't get the units or ingredients correct. I do fix this when I edit the recipe imediately after import, but the errors will linger on in the units and ingredients tables until I delete them. So I suggest that they are first put into temporary tables, and only gets added to the primary tables when the recipe is saved after it has been edited, and the temporary tables gets emptied after the recipe has been saved.

**Comment by vabene1111** [comment]
interesting idea, i see where this is coming from. We also have the issue of non food items being added to the food database trough the shopping function #1137 which kinda goes in the same direction. 

Maybe instead of an additional table one could actually create a flag that indicates if a food is actually used in any recipe and if not simply not show it, at least in the food editing related places or make a special filter to delete those entries 🤔 im not yet 100% sure what to do with this but some kind of soultion will likely happen.

**Comment by SvenErik1968** [comment]
An alternative to the temp tables could be to have some form of a _purge_ function in the _Units_ and _Ingredients_ pages that would delete all entries not associated with any recipes. Then you would not have to manually delete them one-by-one.

**Comment by smilerz** [comment]
> An alternative to the temp tables could be to have some form of a _purge_ function in the _Units_ and _Ingredients_ pages that would delete all entries not associated with any recipes. Then you would not have to manually delete them one-by-one.

I’m currently working on filters and a mass edit feature for food (units, etc) that would get to the same place.

**Comment by smilerz** [comment]
current import allows for editing of ingredients before saving to DB
