### ISSUE TITLE
Language is not saved

### ISSUE THREAD

**Issue by gorgobacka** [TandoorRecipes/recipes#1985]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

The defined language in preferences is not saved for a user.

Steps to reproduce the issue:
1. open the login page (the default is English)
2. log in, go to preferences and change the language (e.g. to German)
3. the language is changed
4. log out
5. use a different browser and open the login page (it's in English)
6. log in with the same use
7. the language is still in English
8. check the preferences (it is set to English)

The expected behavior is that after a user logs in the page is presented in the language defined for that user.

**Comment by vabene1111** [comment]
languages in django (per default) are stored on a per browser basis. The default language is always the browser language so most people will never need to change it anyway.

This can be enhanced in the future by saving this to the db bur for now this suffices as its working for 99,9% of users (because usually browser language = application language preference)

**Comment by gorgobacka** [comment]
Ok. Thanks. I wasn't aware of this. With this knowledge it's fine for me.

Should I leave this issue open for the enhancement or should I close it?

**Comment by vabene1111** [comment]
can be closed, i just forgot it for some reason, thanks for the reminder.
