### ISSUE TITLE
Can't delete unused food in Foods view

### ISSUE THREAD

**Issue by elp3dr0** [TandoorRecipes/recipes#2108]
### Tandoor Version

 1.4.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

In the Foods view, selecting the three dots > delete on a food that is not used in any recipes fails to delete the food. Instead, after clicking 'delete' on the confirmation popup, a toast pop up appears in the bottom right (on a desktop) "Failure. The object you are trying to delete is still used and can't be deleted."

Desired behavior: deleting a food which is not associated with any recipes should remove the food from the list.

**Comment by vabene1111** [comment]
the food is probably be used as part of an ingredient that's part of a step that is not linked to a recipe but is still stored in the database. 

This was implemented because i wanted steps to be reusable across recipes but haven't gotten around to implement whats necessary to do this. 

If you delete it via the admin page you will see the step and can delete it too, I need to implement some fix but unsure how yet

**Comment by vabene1111** [comment]
#2130
