### ISSUE TITLE
images not saved to database

### ISSUE THREAD

**Issue by benneti** [TandoorRecipes/recipes#2137]
### Tandoor Version

1.4.4

### Setup

Others (please state below)

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Other

nixos module with custom settings

### Bug description

Thanks for developing Tandoor recipes!

Since v1.4.4 (meaning on 1.4.1 it was working without a problem) tandoor only uploads the image to the MEDIA_ROOT folder (as name.ext not UUID.ext) but then I get an error in the web interface, see relevant log entry for log happening at the same time!

I am not 100% sure that the occurrence of this coincides with the upgrade or a failed large recipe import from a recipekeeper zip file.

### Relevant logs

```shell
[WARNING] Worker with pid NUMBER was terminated due to signal 31
[INFO] Booting worker with pid: NUMBER
```

**Comment by vabene1111** [comment]
since no application logic regarding images was changed between 1.4 and 1.4.4 i kinda supsect that somthing with the setup went wrong. Can you verify all dependencies are installed correctly ?

you might also want to try to set `DEBUG=1` in `.env` so that you see additional log output (to know why the gunicorn worker crashes)

**Comment by benneti** [comment]
I have `DEBUG=1` as well as `SQL_DEBUG=1` but do not get any log output apart from the one I shared above (or is there another place for the debug log then stdout?).
For completeness the full log (starting up to upload of a picture leading to the termination of the worker):
```

Nov 02 11:43:00 HOSTNAME systemd[1]: Starting Tandoor Recipes server...
Nov 02 11:43:05 HOSTNAME tandoor-recipes-pre-start[601599]: Operations to perform:
Nov 02 11:43:05 HOSTNAME tandoor-recipes-pre-start[601599]:   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, sessions, sites, socialaccount
Nov 02 11:43:05 HOSTNAME tandoor-recipes-pre-start[601599]: Running migrations:
Nov 02 11:43:05 HOSTNAME tandoor-recipes-pre-start[601599]:   No migrations to apply.
Nov 02 11:43:05 HOSTNAME systemd[1]: Started Tandoor Recipes server.
Nov 02 11:43:06 HOSTNAME gunicorn[601746]: [2022-11-02 11:43:06 +0100] [601746] [INFO] Starting gunicorn 20.1.0
Nov 02 11:43:06 HOSTNAME gunicorn[601746]: [2022-11-02 11:43:06 +0100] [601746] [INFO] Listening at: unix:/run/tandor-recipes/tandor-recipes.sock (601746)
Nov 02 11:43:06 HOSTNAME gunicorn[601746]: [2022-11-02 11:43:06 +0100] [601746] [INFO] Using worker: sync
Nov 02 11:43:06 HOSTNAME gunicorn[601760]: [2022-11-02 11:43:06 +0100] [601760] [INFO] Booting worker with pid: 601760
Nov 02 11:45:12 HOSTNAME gunicorn[601746]: [2022-11-02 11:45:12 +0100] [601746] [WARNING] Worker with pid 601760 was terminated due to signal 31
Nov 02 11:45:12 HOSTNAME gunicorn[602204]: [2022-11-02 11:45:12 +0100] [602204] [INFO] Booting worker with pid: 602204
```



Could it be somehow related to this patch applied on nixos: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/tandoor-recipes/media-root.patch (I think it is unlikely as it was working before but just to be sure)?

**Comment by vabene1111** [comment]
i have no clue about nix os sorry, i know tandoor works in docker so the application logic must be correct, the log indicates no errors so this must be some kind of setup issue but due to my lack of nix os understanding there is not much i can do to help.

Since nobody else responded on this issue i will close it for now, you can go to discord and ask around there, maybe someone else can help (i am not sure who created the nix package, it was not to long ago)

**Comment by benneti** [comment]
no problem and thank you anyways
