### ISSUE TITLE
django-js-reverse causes "python manage.py collectstatic_js_reverse" to fail

### ISSUE THREAD

**Issue by ciphermenial** [TandoorRecipes/recipes#2211]
### Tandoor Version

1.4.5

### Setup

Manual Setup

### Reverse Proxy

Others (please state below)

### Other

haproxy

### Bug description

The version of django-js-reverse is failing when running ```python manage.py collectstatic_js_reverse```

The version in use is from https://github.com/ierror/django-js-reverse@7cab78c4531780ab4b32033d5104ccd5be1a246a

I resolved the issue by installing (probably not recommended) https://github.com/BITSOLVER/django-js-reverse by running ```pip install git+https://github.com/BITSOLVER/django-js-reverse```

I was then able to run ```python manage.py collectstatic_js_reverse``` as expected.

**Comment by vabene1111** [comment]
thanks for reporting and linking the correct package. 

The fixes by BITSOLVER look good and one could probably use that repo but maybe I can also just remove that dependency by implementing some small endpoint/release script that generates the URL file for the frontend to use. 

Need to look into that, probably better than depending on yet another outdated dependency but also maybe quite a bit of work, need to look into that.

**Comment by vabene1111** [comment]
ok so for now i updated to https://github.com/BITSOLVER/django-js-reverse/tree/071e304fd600107bc64bbde6f2491f1fe049ec82 

since its pinned to that version i dont really see an issue using it for the time being altough I really want to get rid of some old libraries that are not properly supported anymore. Ideally i think we would use some kind of python script as part of the build process that generates an URL file that the frontend can handle.
