### ISSUE TITLE
 ingredients import from RecetteTek don´t work

### ISSUE THREAD

**Issue by Tropfig** [TandoorRecipes/recipes#2229]
### Tandoor Version

1.4.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Cloudflare

### Bug description

When I Import the .rtk database/backup from RecetteTek app all recepies are imported well, but without ingredients.  Im using SQLlite Database with Tandoor

**Comment by vabene1111** [comment]
can you provide me with an rtk file for me to test this? might be that they changed their format and only need slight tweeking. 

if you dont want to post it feel free to send it to me to info@tandoor.dev

**Comment by vabene1111** [comment]
ok stupid error, dont know why this ever worked because it could not 😂  but its fixed for the next release. 
That said the next release might be a bit further off, if you want to use tandoor you should probably setup a quick and dirty dev environment, import it from recettek and export as tandoor to then import it into the normal version. 
sorry for that inconvenience but some dependencies are broken and fixing that might take a while
