### ISSUE TITLE
Translation into Polish

### ISSUE THREAD

**Issue by WitchDevelops** [TandoorRecipes/recipes#2236]
### Is your feature request related to a problem? Please describe.

Hello! i would like to contribute to this project. I'm an aspiring frontend dev and designer and a Polish native, if you think it's a good idea to translate to some obscure eastern-european languages then I can help :)

### Describe the solution you'd like

Translated into Polish

**Comment by boppy** [comment]
Just see the [contribution page](https://docs.tandoor.dev/contribute/) of the docs. There is info on [how translations are handled](https://docs.tandoor.dev/contribute/#contribute-translations). But sadly, it seems you are late to the party, because polish is one of the three translations that tops out at 100% translated. ;)
