### ISSUE TITLE
Feature Request: Add Author Field

### ISSUE THREAD

**Issue by ModestTG** [TandoorRecipes/recipes#2258]
### Is your feature request related to a problem? Please describe.

This is not related to a problem

### Describe the solution you'd like

I'd like to see an author field added to the system, so you can add who created the recipe. As someone who collects recipes from many different sources I find it very beneficial to be able to see where the recipe came from. Author and Creator are schema tags that exist in the Recipe schema so adding to the import functionality should be straightforward.

### Describe alternatives you've considered

I've considered just creating a cookbook with the name of the person, but that seems like a lot of extra steps for individuals whom might only contribute one recipe to my collection. 

### Additional context

No additional context.

**Comment by vabene1111** [comment]
currently the created_by field tracks who created the recipe, the problem is that this user needs to be an actual user of the application so this field cannot be used. I could create another field but that would mean also creating a means to display this field both in edit, view, search and all other places where it could be required and also adding search functionality for that field. 

I think the easiest soultion (and the one that the importer already kinda handles automatically) is to use keywords. The importer adds the website domain as a keyword automatically but i could also look into having the importer add the "author" attritbute of a recipe (if its given) as a keyword as well. 

Keywords are already very well integrated into all other features of the app and will benefit from all further improvements.

What do you think of that solution?

**Comment by ModestTG** [comment]
Keywords could work. It's not the cleanest solution but since it's already integrated I can use that for now.

**Comment by vabene1111** [comment]
added parsing the author of the page to add it as a keyword automatically
