### ISSUE TITLE
Option to disable Sign-Up / Registration

### ISSUE THREAD

**Issue by besendorf** [TandoorRecipes/recipes#2261]
### Is your feature request related to a problem? Please describe.

With the invite links for spaces, any user can invite other users to the tandoor instance.  This is very problematic for more advanced "enterprise" setups. Especially when one uses LDAP or OIDC a common use case is to disable registration for local users and only allow registration through the Authentication provider to get a single point of truth for the user database and also enforce certain authentication aspects through the provider like 2FA or a password policy.

### Describe the solution you'd like

A configuration option e.g. a ENV variable to disable local sign-ups. Ideally there should also be a more straight forward way to invite already users to a space. I would suggest just entering the username in a field with autocompletion. 

### Describe alternatives you've considered

The only alternative right now is blocking the invite endpoint in the reverse proxy

**Comment by vabene1111** [comment]
to be honest supporting enterprise grade deployments with LDAP is not supported and possible not covered by the license of tandoor. 

Feel free to get in touch with me if you have any enterprise specific needs and we can surely talk about how they could be achieved but those features are not the focus of my free/open source development as these kinds of features don't provide value to the majority of users. 

You can reach me at info@tandoor.dev

**Comment by besendorf** [comment]
Thanks for the response. I understand that this is not the main focus of the project. However I think you missunderstood my use of "enterprise" I don't won't to start a business with a tandoor server but rather my friends and I host several services in a more professional environment where we already use keycloak for authentication.

Also semi-open registrations not ideal from a security point of view. When an adversary gains access to an invite link they could easily create an unlimited number of accounts.

As I said I understand that it is probably not a use case you had in mind I want to ask if that would be something I could help out with and maybe submit a PR. How would you design such a option?

**Comment by vabene1111** [comment]
ok understood.

But what is it that you have with invite links, only a user who has administrator priveledges and owns a space can create invite links, so if no one has these kinds of permission in your space they cannot invite anyone?

or do you see it as a problem that people could create their own space and invite users into that? Maybe we should add a setting to allow or disable autonomous space creation 🤔 

We could also add a setting to allow or forbid the creation of invite links or maybe on a per space level 🤔 

Not sure what the best way from a design perspective is here, to really solve this properly one would need a much more in depth permission model for users. There are several "short term" solutions but I dont want to add to much complexity with for a band aid, what do you think?

We should probably create a diagram of the differnt auth methods and how the different environment variables affect them, maybe it is also time to drop one of the auth methods as supporting 4 different ways is a lot ...

sorry for the rambling but not sure which is the best way forward here so happy to hear some feedback.

**Comment by SergeantBiggs** [comment]
> But what is it that you have with invite links, only a user who has administrator privileges and owns a space can create invite links, so if no one has these kinds of permission in your space they cannot invite anyone?

I think this is just a very specific result of the way we decided to "delegate" permissions, which is not something that is very well supported in the app, and was just the result of me not understanding how the permission model works in general.

The way I thought it worked was similar to tiered permission models with site administrators and group administrators. The site administrator can do anything, and can then delegate certain users to be an admin for a group. But these group admins can only change settings within that group.

Tandoor seems to have a bit of that, insofar that (afaik) space admins can not log into the Django admin panel.

But because space admins can invite other users, compliance with an external authentication system is only possible if you don't give space admin privileges to other people. But they do have value, in a sense that they can invite users that are generally in the server into their specific space, and can manage other settings that the site administrator maybe does not care about.

Especially if one combines it with the idea of an external auth system and multiple spaces. Users could theoretically join, automatically have their own space and then be invited into one or multiple spaces by admins. The space admins could only add users that are already on the server (maybe via a searchable drop-down menu?) but not add new users through sign-up links. As a consequence of that, sign-up links would not even necessary on servers that implement an external auth system. This then ensures compliance and a "single source of truth" for the user database on these types of servers.

In general, if you ask for my opinion for this specific "Issue", I also think a band-aid solution makes little sense. I can work with/around the system currently.

I also think the benefits of a detailed permission system can be quite high, because I think it could cascade nicely into other features (public and private spaces, default permission groups per space instead of per "site", sharing between spaces, separating space administration from user administration, etc).

I definitely like the idea of visualizing the current auth/permission model, and working off that.

These are also just some general ideas from my part, I don't know if any of this makes sense from the perspective of Tandoor and the way it is currently implemented. Also my answer became quite a bit longer than I initially thought :smile: 
But that would be my answer to a general feedback on the current permission and user model of Tandoor.

**Comment by vabene1111** [comment]
thanks for the well written feedback, I agree with most of what you say. 

Since you can work with the way it currently is I will for now not take any action. When I find the time or if someone is willing to contribute it I am happy to first document the current state and then draft and implement a proper auth/permission system. One would need to decive how far it should be taken but i think a little more in depth system would make sense, even for a recipe manager.

**Comment by ishioni** [comment]
@vabene1111 Yeah I'd like to mirror this sentiment. I have an authentik OIDC setup for all of my family and friends, and my wife asked me for a recipe-book application such as this. Out of the selfhosted ones, yours is the only one that can do OIDC at all (yay!), but right now I have to open it up to registration for my oidc users to be able to initially setup accounts. I'd like to allow oidc accounts to be created, but the app signup button to be gone and disabled. Sorry for the me-too post, but I was worried that the discussion was going in such a way that this is some kind of enterprise-grade feature, when in reality a big-enough selfhosted infrastructure needs those features as well ;)

@besendorf thanks for the tip about blocking it on the rev-proxy. That's a nice workaround for now
