### ISSUE TITLE
Gousto.co.uk - Line breaks

### ISSUE THREAD

**Issue by robmc-itpro** [TandoorRecipes/recipes#2401]
### Tandoor Version

Hosted

### Import URL

https://www.gousto.co.uk/cookbook/vegan-recipes/pasta-alla-genovese

### When did the issue happen?

Immediately after importing, in the edit view.

### Response / message shown

```shell
The import doesn’t seem to see the line breaks. For example, the importer pulls in step 1 as follows

Boil a kettleSlice the waxy potatoes (skins on) into 1-2cm thick discsAdd the vegetable stock mix to a large pot of boiled water and bring to a boil over a high heat

When it should be 

Boil a kettle

Slice the waxy potatoes (skins on) into 1-2cm thick discs

Add the vegetable stock mix to a large pot of boiled water and bring to a boil over a high heat
```

**Comment by vabene1111** [comment]
Ok i see what you mean. Generally speaking importing recipes from pages that do not support any structured data (like gusto.co.uk) is a bit tricy and relies on this library https://github.com/hhursev/recipe-scrapers/

Tandoor does nothing than just split the text at its line breaks. One could and try to improve the scraper but since pages like those often change I don't think that success would last a long time. 

So I guess not really much we can do about this sadly
