### ISSUE TITLE
Food properties don't follow 2x conversions

### ISSUE THREAD

**Issue by rinosaur681** [TandoorRecipes/recipes#2537]
### Tandoor Version

1.5.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When using conversions, the property doesn't understand a "double jump". For example I have some lemon juice with the following conversions:

- 1 Tablespoon = 3 Teaspoons
- 1 Whole = 3 Tablespoons
- 1 Tablespoon = 15g

Now my recipe calls for 1 Whole lemon juice which should equal 45g following the above conversions but it only shows the property if I put in an extra middle step of 1 Whole = 45g.

**Comment by vabene1111** [comment]
thanks for the report. You are right, this is currently not possible. The reason is that this can basically be an infinite recursion and would be computationally quite expensive. 

What is currently missing is the base unit feature, i will add that to the next update so you can convert from any custom unit (whole, pcs, ...) to a base unit in either the weight or volume system and it will be able to make all other connections. 

For you that would mean you just have to add the conversion 1 whole = 3 Tablespoons and, since tablespoons are a volumetric unit, 1 Tablespoon = 15g (or in fact any other conversion between a volume and a weight unit for that food) and it will be able to handle it. 

generally speaking this needs some better explanation/documentation

**Comment by hfbauman22** [comment]
Just found Tandoor and loving it so far. I'm also interested in this feature. @vabene1111, what do you anticipate the timeline being for the release that adds this functionality?

**Comment by vabene1111** [comment]
it just needs more docs and usability, everything else is there.
