### ISSUE TITLE
error when using "de" in "kuratierte Liste von Lebensmitteln, Einheiten und mehr importieren"

### ISSUE THREAD

**Issue by BstAA** [TandoorRecipes/recipes#2676]
### Tandoor Version

commit d42d784aeb0595bbc0ed47eb8bbc27ba61b0787d Author: vabene1111  Date:   Tue Aug 29 13:09:38 2023 +0200

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When the above mentioned import works o.k. with "en-US" selection, but gives an error 

`Beim Erstellen einer Ressource ist ein Fehler aufgetreten!`

when selecting "de" i.e. German values

**Comment by sthuber90** [comment]
I observed the same thing with the current latest docker image. I'm using docker compose as well and nginx as proxy

**Comment by djstini** [comment]
It's an older Problem... i wrote a fix for it which allows the ingredients to be created.. the problem is that the properties cant be assigned properly now.

The reason for the problem was that the mapping works by name, which makes sense,, if you already have an ingredient called "Sauerkraut" you wouldnt want to overwrite it.

Now in the Germab translation a few of the ingredients that have different names in english use the same translation in German.

For Examples check the pull request from back then: #2595 

Related issue: #2514

I have time today so imma check out what the problem is now.

**Comment by BstAA** [comment]
> I have time today so imma check out what the problem is now.

THX! I am so new to the project that I can't be a real help

**Comment by djstini** [comment]
No Problem, it seems i overlooked in #2595 that if the list was previously not imported the error would still occur.
