### ISSUE TITLE
Harder to use shopping list on iOS

### ISSUE THREAD

**Issue by borgmanJeremy** [TandoorRecipes/recipes#2942]
### Tandoor Version

8d7b4f614cc61b11d96391a551f951bd6d2673bb

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

Hello,

In commit https://github.com/TandoorRecipes/recipes/commit/8d7b4f614cc61b11d96391a551f951bd6d2673bb the mobile layout was adjusted to put the Food entry in the shopping list on the bottom of the screen while on a mobile layout.

Furthermore, in this commit hitting "Enter" on a mobile keyboard no longer submits the form and the user has to click the green shopping cart icon, which then hides the keyboard. I have 2 questions:

1.) Is it your preference to keep the food entry at the bottom of the screen? This is not my preference but I totally understand if that's the desired path for the project.

2.) Is it intentional that "Enter" on a keyboard no longer submits the form? If not, can I attempt to fix this with a PR?

Thanks for the amazing project!! We have used it daily for months.

**Comment by vabene1111** [comment]
Hi, thanks for the feedback. Lots has been done on shoppin over the recent weeks, it has all been released as beta yesterday. 

1. yes, having it on the bottom and fixed on the list is intentional because its much easier to reach the field this way on mobile in my opinion. What do you think are reasons against doing that?
2. this is fixed in the beta along with a lot of other changes, I would be very interested in hearing your feedback.

**Comment by borgmanJeremy** [comment]
1.) The main reason I did not prefer it was when my keyboard open and closes on mobile the dialog jumps around the screen. It's possible that fixing "Enter" submission will improve this. I will test the beta and report back.

**Comment by vabene1111** [comment]
yes I have noticed that too. Honestly I am a bit undecided, its nice not to have to click at the top of the list but the moving around is annoying as well. Will close this for now but keep it in mind.
