### ISSUE TITLE
Support 'Bakers Percentage' for recipe scaling 

### ISSUE THREAD

**Issue by stleusc** [TandoorRecipes/recipes#3107]
### Describe the solution you'd like

In bread baking, recipes are often written using 'Bakers Percentage'. 
In that case, the only units that are allowed are either NO UNIT or %.
In case of NO UNIT that ingredient would simply not scale.

When showing the recipe, instead of the original percentage and the unit %, the recipe should be scaled.

Example: 
Servings: 402
Servings Text: g
Ingredients:
- 100 % water
- 100 % flour
- 1 % yeast

let TOTAL_PCT be the sum of all number with the unit %, so here 100+100+1 = 201

When viewing the ingredients would show as ('ingredient number'/TOTAL_PCT * SERVINGS)   SERVINGS_TEXT    INGREDIENT:
- 200 g water     (100/201*402=200)
- 200 g flour     (100/201*402=200)
- 2 g yeast     (1/201*402=2)

**Comment by smilerz** [comment]
I don't understand how this is different from how scaling works now.

**Comment by stleusc** [comment]
It is very different:
- the unit in the recipe is % and when VIEWED needs to be replaced with SERVINGS_TEXT
- the value is also not just scaled based on yield but on the SUM of all ingredient percent values

**Comment by stleusc** [comment]
![image](https://github.com/TandoorRecipes/recipes/assets/1132106/ee073eea-d632-4601-92ed-dcf8947c03df)
![image](https://github.com/TandoorRecipes/recipes/assets/1132106/d0c008a2-6207-4cc7-949d-90154733974c)

should be displayed as:
![image](https://github.com/TandoorRecipes/recipes/assets/1132106/d3dd12b2-7183-4c32-ab0d-d6116ad4667f)

**Comment by stleusc** [comment]
Also, since % is 'reserved' so I hear, this logic could be implemented using Pct or Percent as unit.
Even though I fully believe that % should be allowed, for this exact use case.

**Comment by smilerz** [comment]
That's a very niche need and unnecessarily adds to the complexity.

**Comment by jchimene** [comment]
I had a conversation with a professional baker on this topic for a recipe manager.
Would you consider a pull request?

**Comment by smilerz** [comment]
No, the issue isn't writing the code, it's managing the additional complexity.

**Comment by vabene1111** [comment]
I dont understand why you think this is not possible? Just add a property called "Weight" to the ingredients of the recipe and enter them as g instead of % so you have at base scale 100 g flour 100g water 1 g yeast (which everyone can calculate into percentages in their head). Then scale until your property reaches the desired weight. 

Or you dont need a property for that now that I am thinking about it, just use g as the unit and the servings text and change it to the desired quantity, the only thing that would be missing in that case is that its not entered as % but that a minor visual thing and everyone can calculate 100 g -> 100% if the serving is 100g by default. 

What I could see adding add some point is an "entry mode" for percent calculation because I want to add a special entry mode for fractions as well it would probably not be too much complexity, but I will do that myself.
