### ISSUE TITLE
Add X-Real-IP / X-Forwarded-For to nginx docker config

### ISSUE THREAD

**Issue by bjo81** [TandoorRecipes/recipes#3222]
### Is your feature request related to a problem? Please describe.

With the current config, only the nginx-IP is visible to the webapp:

```
::ffff:172.26.0.4 - - [18/Jul/2024:12:32:06 +0200] "GET /service-worker.js HTTP/1.0" 200 39291 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
```

### Describe the solution you'd like

Add
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
to the config.

**Comment by vabene1111** [comment]
Thanks for the idea. The thing is I really hate changing anything in the installation process because every time in the past I have done so some edge case came up that broke things. 
This leads me to the question: what benefit does this change have? The application works without from what I know and most people will have a reverse proxy which typically sets these variables. If one does not have a reverse proxy setup its easy to change the nginx config according to personal preferences. 

So is it necessary to make this change in the default config?

**Comment by bjo81** [comment]
I thought using nginx as reverse proxy is somehow a requirement for the official supported version. If not and I can use traefik directly to the app itself, it's not needed.
