### ISSUE TITLE
Automatically Select Keywords When Importing Recipes via URLs

### ISSUE THREAD

**Issue by steve2211** [TandoorRecipes/recipes#3263]
### Is your feature request related to a problem? Please describe.

I’m always frustrated when I import multiple URLs at once into my list of recipes because, although the import process works well, there is no option to activate the found keywords. This makes it difficult to efficiently organize and search through the imported recipes.

### Describe the solution you'd like

When importing recipes via URLs, all found keywords should be selected by default instead of having to select them manually.

### Describe alternatives you've considered

Importing all recipes one by one and manually selecting all keywords for each of them.

**Comment by vabene1111** [comment]
I understand, the reason I do not do this by default is that in my experience keywords on most recipe pages are pretty bad, because they add so many or sometimes unrelated keywords. That is why only keywords you already have are automatically selected on imports. 

Still I see what you mean, I could probably add a setting to the import page when importing multiple urls

**Comment by steve2211** [comment]
Thank you for your response.

I wasn’t aware that existing keywords are automatically selected. This is new information for me, and I will work with that for now. However, I still believe that having a setting to automatically select all found keywords could be very practical. It would save time and effort, especially when dealing with a large number of recipes.
