### ISSUE TITLE
Enhancement of UI

### ISSUE THREAD

**Issue by dhruvi6071** [TandoorRecipes/recipes#3341]
### Is your feature request related to a problem? Please describe.

There is a section on home page which can be batter of the ui feature is updated. 
<img width="853" alt="image" src="https://github.com/user-attachments/assets/70192e01-d1ec-4578-bec1-e0cfff8cc664">
if we put logo in center and also change the bold font color it will make more eye pleasant for users and also more text for reading get a boring experience.

### Describe the solution you'd like

I would like to improve it as for picture visual. I would like to put logos in middle of the content and also down the number of words. Try to not make fonts bolder instead change the color of it.

### Describe alternatives you've considered

If you don't like to change the color of the bold fonts then change the text into one color but rather only put important words in it. and also remove link option and make the whole logo and text the link so that user just need to point on it and of he click it it can guide to read more section.

### Additional context

<img width="853" alt="image" src="https://github.com/user-attachments/assets/b205e792-d52b-464c-9aaa-b0657d6d6efb">

**Comment by smilerz** [comment]
the front end is currently being rewritten

**Comment by dhruvi6071** [comment]
I would like to offer my assistance in enhancing your UI design. With my ability to identify and evaluate effective design principles, I can provide valuable input to improve the overall user experience and visual appeal. I am confident that my skills can contribute to refining the aesthetics and functionality, ensuring the design is both user-friendly and visually engaging. Please let me know how I can assist in this process.

**Comment by smilerz** [comment]
> I would like to offer my assistance in enhancing your UI design. 

[This ](https://github.com/TandoorRecipes/recipes/tree/feature/vue3) is the branch for the next version.  Please join the discord to discuss any specific things you would like to build.

**Comment by vabene1111** [comment]
Hi, help making the design better is always appreciated. As smilerz mentioned the vue 3 branch is the next version with a completly new UI. Since a lot of it is very early WIP its hard to tell you any place to start working on, feel free to look around and if you see anything to improve just open an issue outloining your ideas and I will let you know if its a good idea to get going at it. 

The screenshots you prvided are from the website, which is not open source. Still if you have any ideas feel free to download the html and just edit it. Its a super simple and static page without much fancy stuff.

**Comment by dhruvi6071** [comment]
Okay i will try my best to improve it.
