### ISSUE TITLE
1.5.25 tagged release doesn't have built container image

### ISSUE THREAD

**Issue by rjhenry** [TandoorRecipes/recipes#3465]
### Tandoor Version

1.5.24

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

Not relevant; this is GitHub side!

### Bug description

The tagged release 1.5.25's GitHub action to build the Docker container failed:
https://github.com/TandoorRecipes/recipes/actions/runs/12535515717
Interestingly, the container for the same commit to `master` also failed:
https://github.com/TandoorRecipes/recipes/actions/runs/12535512464

It looks like nothing was _wrong_ so much as the Actions runner got stuck and I wouldn't be surprised if a re-run of the Action sorted the issue.

Thanks for your fantastic project!

**Comment by Akruidenberg** [comment]
Same here. My custom dockerfile did not work. :)

**Comment by christian-heusel** [comment]
I think the build timed out once again 🤔

**Comment by christian-heusel** [comment]
Is there something wrong on my side? I think this issue should be reopened:
```
$ docker compose up -d && docker compose logs -f
[+] Running 1/1
 ✘ web_recipes Error manifest for vabene1111/recipes:1.5.25 not found: manifest unknown: manifest unknown                                                1.3s 
Error response from daemon: manifest for vabene1111/recipes:1.5.25 not found: manifest unknown: manifest unknown
```

**Comment by vabene1111** [comment]
i get an email every time it fails, so thanks for posting but sadly I know :) the problem is (as usual) the arm cryptography build which fails for some reasons sometimes. 

Tandoor 2 will no longer support this architecture which will make the builds much more reliable. For now I am just restarting the job once more since I did not change anything as far as I know its likely an upstrem problem. Maybe it works today if not I will have to take another look. If anyone knows why it fails feel free to PR/tell me the fix.
