### ISSUE TITLE
Spacing for steps without ingredients

### ISSUE THREAD

**Issue by Wesleyl89** [TandoorRecipes/recipes#642]
Is there a way to keep the instructions part always on the right side even when the step doesn't require (new) ingredients?

I've tried to do it with a dummy ingredient and works, but this will also add that dummy ingredient in the overview ingredient list.

![image](https://user-images.githubusercontent.com/5655317/120614324-63c53700-c457-11eb-8d73-1f6d7ee38c1a.png)

Another thing is that the ingredients per step are not aligned with other steps, which could look a little bit cleaner if it was.

edit: I see that I chose the wrong issue type, since this is not a setup issue :)

**Comment by vabene1111** [comment]
Hmm this is interesting. I definitly see you point but some people also like the iweder area to allow for more text.

but i guess shorter lines are read more easily so i guess i will change this

**Comment by Wesleyl89** [comment]
I can definitely see the other peoples point of view. 

I've tried to do it as a header, but that way it will show up in the ingredient list:
![image](https://user-images.githubusercontent.com/5655317/120659656-dac5f400-c486-11eb-8cac-1e82451b786b.png)
![image](https://user-images.githubusercontent.com/5655317/120660019-33958c80-c487-11eb-811a-f52b6d8f8c6d.png)

**Comment by vabene1111** [comment]
i guess there needs to be a per-step setting for this

**Comment by vabene1111** [comment]
ok changed this for now but will likely change it again in the future to make everying more evenly aligned

**Comment by igorsantos07** [comment]
Sorry for necro-bumping, but @vabene1111 what's the state of this problem? I would suggest reopening the issue, as it's still present nowadays.
The only step-related setting I see is "Show Step Ingredients", which doesn't seem related and, indeed, doesn't change anything related to the shift of alignment on ingredient-less steps.

I wonder if this could be configured as a user-wide (or system-wide??) option instead of being per-step? Or maybe both, so there would be a default that could be overridden on specific steps instead.

And you're right about shorter lines being easier to read - IIRC, print media usually strives to 80 words per line, or something like that.

**Comment by reneas** [comment]
sorry for necro-bumping again but i wasnt sure if i should open a new issue for this.
has there been any development on this?

**Comment by vabene1111** [comment]
the old issue was tandoor 1 so if you have something similar in tandoor 2 please open a new issue. Feel free to reference this one.
