### ISSUE TITLE
Recipe Soft Delete and Delete constraint check

### ISSUE THREAD

**Issue by JadElClemens** [TandoorRecipes/recipes#950]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 
Current Version: 0.16.8
Ref: 6c22fb0ef49ce2d389624ebdb286464bf8089d93

### Bug description
I am unable to delete recipe 1, which was a test recipe - have had no issue deleting other recipes. I can get to the delete confirmation page, but confirming that I want to delete the recipe returns an HTML error 500 and the recipe is not deleted.

docker-compose logs can be found here: https://clbin.com/0ZBML
Looks like my entire log from first start but the relevant portion is the last 10 or so requests.

**Comment by vabene1111** [comment]
ok so for now the next version will at least show a proper error page if a recipe cannot be deleted due to some kind of constraint 
![image](https://user-images.githubusercontent.com/6819595/137951291-08a372c9-81ea-44c7-87f9-56352bd1f19f.png)

in general we need to 
- [ ] add a (possibly generic) page to review constraints when deleting something
- [ ] add a soft delete state for recipes (maybe as the default)
- [ ] allow linking to some kind of "detail" page for all kinds of models since those have been removed when we moved everything to the frontend
- [ ] allow "delete anyway" to delete the recipe/obj and all related objects blocking the delete

**Comment by kdheepak** [comment]
Hi. I'm having the same issue. When I try to delete a recipe, I get a reference in the "ViewLog". How do I remove it from the ViewLog in order to then delete it?

**Comment by vabene1111** [comment]
the view log needs to be changed to cascade instead of preventing a delete, i will fix this in the next release.
