### ISSUE TITLE
NGINX issues since 0.17 

### ISSUE THREAD

**Issue by auanasgheps** [TandoorRecipes/recipes#959]
### Version
Version: 0.17.2

### Bug description
Since the update to 0.17, here's what looks like.

If I go to Space settings, it says I have 20 recipes (correct). 

Something in the upgrade went wrong. What should I do? I can't access my recipes!

![immagine](https://user-images.githubusercontent.com/20586878/137514365-6393c53b-df82-442d-ae5d-cbcf27b37eae.png)

**Comment by smilerz** [comment]
@auanasgheps how is Tandoor setup (manual, docker, other)?  can you share the logs?  also if hit F12 the developer console might provide some additional context.

**Comment by MaxJa4** [comment]
I had the same exact issue since 0.17.0...
My nginx reverse proxy was the cause, I had to add the following lines inside the nginx site config (in the location region):
`proxy_set_header X-Forwarded-Proto $scheme;`
I also added `proxy_set_header Host $Host;`, but I don't know if that's necessary.
This is partially mentioned in the [FAQs](https://docs.tandoor.dev/faq/)

**Comment by auanasgheps** [comment]
This is may config before it broke down (pre 0.17).

If I add `proxy_set_header Host $Host;` I get "Bad Request (400)" and the page doesn't load.
In the past I've already fought with Recipes and Nginx. Here we go again.

```shell
    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app recipes-app;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by vabene1111** [comment]
So first of all the included nginx config and all recommended/documented setups have been tested and were working. 

The paths are not absolute but django has several build in ways that manage constructing paths, if a proxy setup in front of django does not pass trough the correct headers than django is not able to determine where it is actually running from and thus cannot tell the frontend components the correct routes to make request to. 

From what i can see @auanasgheps you are getting requests blocked because django thinks that its running on http but it actually is served over https. This can happen if the proxy enforces https for the main requests (which it is able to do since it passes trough it) but it cannot rewrite the urls that django determines it needs to use for making api requests. 

Please make sure you set `proxy_set_header Host $http_host;` (http_host not host as stated in the docs and issue #953) the other header `proxy_set_header X-Forwarded-Proto $scheme;` looks correct. If that does not help please remove all configuration entries from your nginx config that are not clearly mentioned in the installation guide and verify the problem still exists. If it does please post detailed information about your setup (folder locations, OS versions, all relevant config files env/nginx/etc.)

**Comment by MaxJa4** [comment]
My nginx config (of the host system, as reverse proxy) looks like this:

`server {
    if ($host = SUB.DOMAIN.TLD) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name SUB.DOMAIN.TLD;
    listen 80;
    return 404; # managed by Certbot
}
server {
    server_name SUB.DOMAIN.TLD;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/SUB.DOMAIN.TLD/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/SUB.DOMAIN.TLD/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        location / {
                proxy_pass http://127.0.0.1:PORT;
                proxy_redirect http://127.0.0.1:PORT https://SUB.DOMAIN.TLD;
                proxy_set_header Host $Host;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}`

Be sure to replace SUB.DOMAIN.TLD (6x) and PORT (2x) in all spots ofc. This is by far not a perfect config but it works for me. If you don't use certbot or letsencrypt, you might need to change some stuff.

**Comment by vabene1111** [comment]
Ok to from djangos side of things everything looks correct but in the requests you send i cannot see any of the frontend javascript files being requested. 

The mixed content warning, even tough it is gone now, is understandable because if django thinks that it is running under http (which it might if some header breaks) it will render the html containing http links. Even if your proxy would upgrade them when they are executed the browser would think that its mixed content and thus block the requests / show errors.

One thing the django log shows for sure is that the connection refused response that you are seeing in your console comes somewhere from your proxy stack as the requests dont actually make its way to django but get canceled somewhere in front. You could try to visit the /api/xyz url manually and see if the connection refused happens there as well and try to debug which part of your proxy kills that request.

What i see is that your default config uses `proxy_set_header Host $host;` and not `proxy_set_header Host $http_host;`. I am not sure if this is a problem but i remember that we added this parameter for a reason, just not which reason.

**Comment by auanasgheps** [comment]
I can replicate the issue with a clean linuxserver/swag istance.

- I've copied my current nginx/swag stack and adjusted the configuration to bind  the test istance to another folder
- Made some basic changes to run the proxy (SSL generation)
- Rename recipes.subdomain.conf.sample to recipes.subdomain.conf and make the changes to work (port and container name)

1st error: CSFR login failure
2nd error (if I'm already logged in): nothing loads, but I might have spotted where the problem is: the error below **does not list the port**. My reverse proxy is not running on 443 but 8080!
Might this be related to Django? The service is exposed on 8080 from both the proxy and the recipes front end.

Additionally, are you willing to try this setup? You should be able to replicate. In the meantime I'll open an issue with the linuxserver guys.

![image](https://user-images.githubusercontent.com/20586878/138072091-f22e91d0-ea3a-4c99-9a88-5b86d300b7d7.png)

**Comment by vabene1111** [comment]
Ok now that i read your post again and the swag post as well: You are saying your server runs under 8080 and django makes requests to 443 which obviously get refused. 

This means that the headers required for django to know under which port it runs are not set correctly thus it returns the wrong api urls. There are two options i see here, either run tandoor on 443 (which is see no reason why not to do this since you are using a reverse proxy with proper domains and having non default ports is annoying anyway) or find out which headers are required for django to know the port of your request. 

I know people run tandoor on non default ports and my dev setup does this as well so it should not be a problem but i could also probably implement that you can set the port from the reverse proxcy using a header like detailed here https://docs.djangoproject.com/en/dev/ref/settings/#use-x-forwarded-port

**Comment by auanasgheps** [comment]
I wanted to do a step back but Django really doesn't like the Swag container.

I adopted the full stack as per your documentation, by adding a "dummy" nginx that only serves Recipes. Works great but I'll never expose that container to the internet.

So I though to place my main swag in front of the dummy nginx. Not an elegant solution but still viable.

Well, the page errors out because the browser tries to reach _recipes-nginx_ which is the name of the dummy nginx, but I'm connected to the swag nginx with my full domain name, so django is messing up with whatever swag is trying to do.

I still haven't found the time to update to develop branch, I won't do it before Saturday. I hope will help us understand this behaviour.
 
![immagine](https://user-images.githubusercontent.com/20586878/138366399-a9fa3191-a9c8-4667-866c-1946d6e340d6.png)

**Comment by auanasgheps** [comment]
@vabene1111 sorry for the delay, I got carried by other things. Do I still need the develop branch to see the headers?

**Comment by vabene1111** [comment]
No this has since been released. There have also been some fixes so your problems might even be resolved.

**Comment by auanasgheps** [comment]
eheh the problem is still here!

So here are the headers. They look correct to me...

```
HTTP_CONNECTION:close
HTTP_HOST:recipes.mydomain.tld
HTTP_X_FORWARDED_FOR:10.8.0.2
HTTP_X_FORWARDED_HOST:recipes.mydomain.tld
HTTP_X_FORWARDED_PROTO:https,https
HTTP_X_FORWARDED_SSL:on
HTTP_X_REAL_IP:10.8.0.2
HTTP_SEC_CH_UA:"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"
HTTP_SEC_CH_UA_MOBILE:?0
HTTP_SEC_CH_UA_PLATFORM:"Windows"
HTTP_UPGRADE_INSECURE_REQUESTS:1
HTTP_DNT:1
HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_USER:?1
HTTP_SEC_FETCH_DEST:document
HTTP_REFERER:https://recipes.mydomain.tld:8080/search/
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_ACCEPT_LANGUAGE:it-IT,it;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6
HTTP_SEC_GPC:1
HTTP_COOKIE:csrftoken=blablabla sessionid=blablabla
```

**Comment by vabene1111** [comment]
is this maybe the problem `HTTP_X_FORWARDED_PROTO:https,https`  ? i dont think its correct for https to be in there twice ? in my instance it looks like this `HTTP_X_FORWARDED_PROTO:https` i think one of the proxies does not remove the header and just appends the https. 

Maybe try in you proxy to set and not append it to just `https` ? Other than that i am at a loss here, no idea on how to help you further. If you want we can shedule a meeting next week were i would look at your setup with anydesk, teamviewer or something similar to help you fix the issue.

**Comment by auanasgheps** [comment]
> is this maybe the problem `HTTP_X_FORWARDED_PROTO:https,https` ? i dont think its correct for https to be in there twice ? in my instance it looks like this `HTTP_X_FORWARDED_PROTO:https` i think one of the proxies does not remove the header and just appends the https.

Correct, this was my mistake, I may have added this header when playing around with settings.

So I finally found the time to play around a little bit and **I FIXED IT!!!!**

Give me some time to wrap it up and explain. As you suspected, the issue is in Swag configurations that don't pass the headers that Django wants (but to be fair with them, they work correctly with all other sites).

I'll post updates soon.

**Comment by auanasgheps** [comment]
First of all, this problem only affects you if you're using [linuxserver/swag](https://github.com/linuxserver/docker-swag) and you are hosting it on a port that is not 443 (nginx port, not Recipes). The default config works when using 443!

**Analysis**
By default, [linuxserver/swag](https://github.com/linuxserver/docker-swag) sets two headers that Django doesn't like:
- `proxy_set_header X-Forwarded-Host $host;`
- `proxy_set_header Host $host;`

If I change these two headers from `$host` to `$http_host`, Recipes works perfectly!

**The Problem**
linuxserver/swag has a file with generic headers that are required by many apps, including the aforementioned headers, called [proxy.conf](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf). We can't get rid of this file, because includes a lot of configs that are also required for Recipes.

I'm not super expert in Nginx, but looks like there's no way to **override** a config: if I set it in the config file, it gets declared twice.

**Solution**

There are different ways to approach the issue, the one that suits my mental order is:
- Creare a copy of `proxy.conf`
- Replace `proxy_set_header X-Forwarded-Host $host;` and `proxy_set_header Host $host;` to 
   - `proxy_set_header X-Forwarded-Host $http_host;` and `proxy_set_header Host $http_host;`
- Update `recipes.subdomain.conf` to use the new file
- Restart the linuxserver/swag container and Recipes will work again

You could also copy the whole content of proxy.conf to recipes.subdomain.conf and set the correct values, but the file will look messy.

linuxserver/swag talks directly to Django front end, without the dedicated nginx instance.

**Final words**
I cannot make a PR to linuxserver/swag because their default config works if using standard ports. 
Can we add this information to your wiki? I can make the PR if you don't have the time.

**Comment by auanasgheps** [comment]
@smilerz shall we document what I've discovered in the official doc?

**Comment by smilerz** [comment]
That would be great if you can submit a PR

**Comment by vabene1111** [comment]
Possibly the FAQ or some other section you find fitting

**Comment by auanasgheps** [comment]
done :)

**Comment by Nabukodonosor** [comment]
This works for me, but it doesn't load recipe images. Anyone knows why?
